spring.application.name=backend-springboot
# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:smart_bus.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8081